### ISSUE TITLE
when html is created and three dots

### ISSUE THREAD

**Issue by tik9** [wernerglinka/metalsmith-markdown-partials#1]
***4 questions***

1. I wonder when the index.html file will be created. Is there a listener to check whether the index.md has changed? Or do I need another tool because your tool is dealing with partials?

2. What are the three dots for? I think they tell the parser that it is a partial: 
... 
<text>
...

3. example
var mdPartials = require('metalsmith-markdown-partials');
...
.use(mdPartials({"libraryPath": './dev/content/library/'}))
...
- Is this code for the app.js in node?
- What is the `.use`, the `.` here? Is it related to REPL that uses `. syntax` ?

**Comment by wernerglinka** [comment]
This plugin is used with the Metalsmith Staic site Generator. The HTML is created when running Metalsmith. See https://metalsmith.io/ for an explanation, it will make things clear.

The three dots are just in indicator that other code will be there.
